spring.application.name=tutorfinder

spring.datasource.url=jdbc:mysql://localhost:3306/tutorfinderDB?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=thescholarsbay@gmail.com
spring.mail.password=txoq jkcl kwmk rsal
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

server.tomcat.max-swallow-size=20971520

# JWT Configuration
jwt.secret=413F4428472B4B6250655368566D5970337336763979244226452948404D6351
jwt.access-token-expiration=86400000
jwt.refresh-token-expiration=604800000
jwt.issuer=tutorfinder
jwt.cookie-name=jwt-token
